version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: busra
      POSTGRES_PASSWORD: busra123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - library-network

  app:
    build: .  # Önemli: Dockerfile'ın bulunduğu klasör
    container_name: library-app-2
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/library_db
      SPRING_DATASOURCE_USERNAME: busra
      SPRING_DATASOURCE_PASSWORD: busra123
    depends_on:
      - db
    networks:
      - library-network

volumes:
  postgres-data:

networks:
  library-network:
    driver: bridge
